author: AVM
name: avm-repos
description: Gets AVM repositories based on GH app installation and outputs them as a JSON array.
inputs:
  repositories:
    description: "Target repositories, comma separated list to select specific repositories: 'avm-res-keyvault-vault'."
    default: "All"
  repositoriesToSkip:
    description: "Repositories to skip, comma separated list of repos to skip, e.g. 'avm-template'."
    default: ""
  outputDirectory:
    description: "Output directory for the repository data"
    default: "${{ github.workspace }}"
  metaDataFilePath:
    description: "Path to the meta-data.csv file used to determine expected archive state for repositories."
    default: "${{ github.workspace }}/repository-management/repository-sync/config/repository-metadata.csv"
  clientId:
    description: "GitHub App Client ID"
    required: true
  privateKey:
    description: "GitHub App Private Key"
    required: true
outputs:
  matrix:
    description: The repository data
    value: ${{ steps.matrix.outputs.matrix }}
  matrixParallel:
    description: The number of parallel jobs to run
    value: ${{ steps.matrix.outputs.matrixParallel }}

runs:
  using: composite
  steps:
    - name: Create GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        client-id: ${{ inputs.clientId }}
        private-key: ${{ inputs.privateKey }}
        owner: ${{ github.repository_owner }}

    - name: Generate Matrix
      id: matrix
      run: |
        $matrixParallel = 5
        Write-Output "matrixParallel=$matrixParallel" >> $env:GITHUB_OUTPUT

        $repositories = "${{ inputs.repositories }}"
        if($repositories -eq "All") {
          $repositories = @()
        } else {
          $repositories = $repositories -split ','
        }

        Write-Host "Repositories to include: $(ConvertTo-Json $repositories)"

        $repositoriesToSkip = "${{ inputs.repositoriesToSkip }}"
        if($repositoriesToSkip -eq "") {
          $repositoriesToSkip = @()
        } else {
          $repositoriesToSkip = $repositoriesToSkip -split ','
        }

        Write-Host "Repositories to skip from input: $(ConvertTo-Json $repositoriesToSkip)"

        $matrix = @(& "${{ github.action_path }}/scripts/Get-RepositoriesWhereAppInstalled.ps1" `
          -repoFilter $repositories `
          -outputDirectory "${{ inputs.outputDirectory }}" `
          -additionalReposToSkip $repositoriesToSkip `
          -metaDataFilePath "${{ inputs.metaDataFilePath }}")

        $matrixJson = ConvertTo-Json $matrix -Depth 10 -Compress
        Write-Host (ConvertTo-Json $matrix -Depth 10)
        Write-Output "matrix=$matrixJson" >> $env:GITHUB_OUTPUT
      shell: pwsh
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Upload Repo Logs Json
      if: always() && hashFiles('issues.log.json') != ''
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: issues.log.json
        path: issues.log.json

    - name: Repo Error
      if: always() && hashFiles('issues.log.json') != ''
      run: |
        $issueLogJson = Get-Content -Path "${{ github.workspace }}/issues.log.json" -Raw
        $issueLog = ConvertFrom-Json $issueLogJson
        $issueLog | Where-Object { $_.severity -eq "error" } | ForEach-Object {
          echo "::error title=$($_.repoId) has issues::$($_.message)"
        }
        $issueLog | Where-Object { $_.severity -eq "warning" } | ForEach-Object {
          echo "::warning title=$($_.repoId) has issues::$($_.message)"
        }
      shell: pwsh
