#Requires -Version 7.4
#Requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.5.0' }

# Spec section 5: "A pre-commit Pester test fails if any file in src/ contains
# a BOM or a CRLF." This test enforces that invariant. It is intentionally a
# Unit test (no -Tag Smoke/Integration) so it runs as part of every
# ./build.ps1 pre-commit and ./build.ps1 ci invocation.
#
# Why this matters even though .gitattributes already enforces LF:
#   - .gitattributes only normalises on commit. Files dropped into the working
#     tree by editors, IDEs, or generated by helper scripts can sit with CRLF
#     line endings or a UTF-8 BOM and ship to PR review before any commit
#     gate sees them.
#   - PSScriptAnalyzer is lenient about BOMs (it parses fine), so lint will
#     not catch them.
#   - On Linux runners, BOM-prefixed psd1 files trip Test-ModuleManifest with
#     an opaque "the term is not recognized" error because the first line is
#     parsed as 'BOM#Requires...' instead of '#Requires ...'. Catching it
#     here turns that into a clear, file-named failure.

BeforeAll {
    $script:repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..' '..' '..' '..')
    $script:srcRoot  = Join-Path $script:repoRoot 'src'

    # Extensions that .gitattributes marks as 'text eol=lf'. Anything else
    # (.exe, .dll, .png, .zip, ...) is binary and excluded by extension.
    # Keep this list in sync with .gitattributes.
    $script:textExtensions = @(
        '.ps1', '.psm1', '.psd1',
        '.md',
        '.yml', '.yaml',
        '.json', '.toml',
        '.sh',
        '.bicep', '.tf'
    )

    function script:Get-AvmSourceTextFile {
        Get-ChildItem -LiteralPath $script:srcRoot -Recurse -File |
            Where-Object { $script:textExtensions -contains $_.Extension.ToLowerInvariant() }
    }

    function script:Test-AvmHasUtf8Bom {
        param([Parameter(Mandatory)] [string] $Path)
        $bytes = [System.IO.File]::ReadAllBytes($Path)
        return ($bytes.Length -ge 3 -and
                $bytes[0] -eq 0xEF -and
                $bytes[1] -eq 0xBB -and
                $bytes[2] -eq 0xBF)
    }

    function script:Test-AvmHasCrlf {
        param([Parameter(Mandatory)] [string] $Path)
        # Read raw bytes (not a string) so PowerShell does not normalise line
        # endings on us during the read. A single 0x0D byte is enough.
        $bytes = [System.IO.File]::ReadAllBytes($Path)
        for ($i = 0; $i -lt $bytes.Length; $i++) {
            if ($bytes[$i] -eq 0x0D) { return $true }
        }
        return $false
    }
}

Describe 'src/ encoding and line-ending invariants' {
    Context 'discovery' {
        It 'finds at least one text file under src/ (sanity check)' {
            $files = script:Get-AvmSourceTextFile
            $files.Count | Should -BeGreaterThan 0
        }
    }

    Context 'no UTF-8 BOM' {
        It 'every text file under src/ is UTF-8 without BOM' {
            $bomFiles = @()
            foreach ($file in script:Get-AvmSourceTextFile) {
                if (script:Test-AvmHasUtf8Bom -Path $file.FullName) {
                    $relative = $file.FullName.Substring($script:repoRoot.Path.Length + 1)
                    $bomFiles += $relative
                }
            }
            $bomFiles | Should -Be @() -Because (
                "spec section 5 requires UTF-8 without BOM. To fix, re-save the file " +
                "with UTF-8 (no BOM) encoding. Offenders: $($bomFiles -join ', ')")
        }
    }

    Context 'no CRLF line endings' {
        It 'every text file under src/ uses LF line endings only' {
            $crlfFiles = @()
            foreach ($file in script:Get-AvmSourceTextFile) {
                if (script:Test-AvmHasCrlf -Path $file.FullName) {
                    $relative = $file.FullName.Substring($script:repoRoot.Path.Length + 1)
                    $crlfFiles += $relative
                }
            }
            $crlfFiles | Should -Be @() -Because (
                "spec section 5 requires LF line endings. .gitattributes will " +
                "normalise on commit but the working tree must already be LF. " +
                "To fix on Windows: dos2unix <file>, or re-save in your editor " +
                "with LF endings. Offenders: $($crlfFiles -join ', ')")
        }
    }
}
