#Requires -Version 7.4
param(
    [Parameter(Mandatory)]
    [System.Collections.IDictionary] $Convention
)

$Convention.NativeReadmeExpected = 0
if ($Convention.ReadmeInputs.Count -gt 0) {
    Describe 'Bicep README <IssuePath>' -ForEach $Convention.ReadmeInputs {
        $Convention.NativeReadmeExpected++
        It 'exists alongside its source' -Tag 'avm.bicep.docs-missing' {
            ($null -ne $Case.Current) | Should -BeTrue -Because "run 'avm docs' and commit README.md"
        }
        if ($null -ne $Case.Current) {
            $Convention.NativeReadmeExpected++
            It 'matches generated bytes except verified grouping-comment omissions' -Tag 'avm.bicep.docs-stale' {
                $identical = [System.Linq.Enumerable]::SequenceEqual([byte[]]$Case.Current, [byte[]]$Case.Expected)
                ($identical -or $Case.MissingExampleComments -gt 0) |
                    Should -BeTrue -Because "run 'avm docs' and commit the generated README.md"
            }
            if ($Case.MissingExampleComments -gt 0) {
                $Convention.NativeReadmeExpected++
                It 'includes the generated JSON-example grouping comments' -Tag 'avm.bicep.docs-example-comments', 'severity:warning' {
                    $Case.MissingExampleComments | Should -Be 0 `
                        -Because "$($Case.MissingExampleComments) generated JSON-example grouping comments are missing; 'avm docs' will restore them"
                }
            }
        }
    }
}
