<#
.SYNOPSIS
    Generate the checked-in public cmdlet reference.

.DESCRIPTION
    Imports Avm.Authoring, reads comment-based help for every exported
    function, and writes deterministic Markdown pages under docs/reference.
    Use -Check to fail when the checked-in reference is missing, stale, or
    contains pages for functions that are no longer exported.

.PARAMETER OutputPath
    Destination directory for the generated Markdown reference.

.PARAMETER Check
    Compare generated content with the destination without writing files.

.EXAMPLE
    ./scripts/Generate-AvmCmdletDocumentation.ps1

.EXAMPLE
    ./scripts/Generate-AvmCmdletDocumentation.ps1 -Check
#>

#Requires -Version 7.4

[CmdletBinding()]
param(
    [string] $OutputPath = (Join-Path $PSScriptRoot '..' 'docs' 'reference'),

    [switch] $Check
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$manifestPath = Join-Path $repoRoot 'src' 'Avm.Authoring' 'Avm.Authoring.psd1'
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$lineFeed = "`n"
$generatedNotice = '<!-- Generated by scripts/Generate-AvmCmdletDocumentation.ps1. Do not edit by hand. -->'

function ConvertTo-MarkdownText {
    [CmdletBinding()]
    param(
        [AllowNull()]
        [object] $Value
    )

    if ($null -eq $Value) {
        return ''
    }

    $text = if ($Value -is [string]) {
        $Value
    }
    elseif ($Value -is [System.Collections.IEnumerable]) {
        @($Value | ForEach-Object { ConvertTo-MarkdownText -Value $_ }) -join $lineFeed
    }
    elseif ($Value.PSObject.Properties['Text']) {
        @($Value.Text) -join $lineFeed
    }
    else {
        [string] $Value
    }

    $text = $text -replace "`r`n?", $lineFeed
    $lines = @($text -split $lineFeed | ForEach-Object { $_.TrimEnd() })
    return ($lines -join $lineFeed).Trim()
}

function ConvertTo-MarkdownTableCell {
    [CmdletBinding()]
    param(
        [AllowNull()]
        [object] $Value
    )

    $text = ConvertTo-MarkdownText -Value $Value
    return ($text -replace '\|', '\|' -replace "`n", '<br>')
}

function Get-ParameterTypeName {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Management.Automation.ParameterMetadata] $Parameter
    )

    if ($Parameter.ParameterType -eq [switch]) {
        return 'Switch'
    }

    $typeName = $Parameter.ParameterType.Name
    if ($Parameter.ParameterType.IsArray) {
        $typeName = '{0}[]' -f $Parameter.ParameterType.GetElementType().Name
    }
    return $typeName
}

function Get-CommandReferenceContent {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Management.Automation.CommandInfo] $Command
    )

    $help = Get-Help -Name $Command.Name -Full
    $synopsis = ConvertTo-MarkdownText -Value $help.Synopsis
    $description = ConvertTo-MarkdownText -Value $help.Description
    if (-not $synopsis) {
        throw "Public cmdlet '$($Command.Name)' has no .SYNOPSIS help."
    }
    if (-not $description) {
        throw "Public cmdlet '$($Command.Name)' has no .DESCRIPTION help."
    }

    $commonParameters = @(
        [System.Management.Automation.PSCmdlet]::CommonParameters
        [System.Management.Automation.PSCmdlet]::OptionalCommonParameters
    )
    $helpParameters = @{}
    foreach ($parameterHelp in @($help.Parameters.Parameter)) {
        $helpParameters[[string] $parameterHelp.Name] = $parameterHelp
    }

    $parameters = @(
        $Command.Parameters.Values |
            Where-Object Name -NotIn $commonParameters |
            Sort-Object -Property Name
    )
    foreach ($parameter in $parameters) {
        $parameterHelp = $helpParameters[$parameter.Name]
        if ($null -eq $parameterHelp -or -not (ConvertTo-MarkdownText -Value $parameterHelp.Description)) {
            throw "Public cmdlet '$($Command.Name)' parameter '-$($parameter.Name)' has no .PARAMETER help."
        }
    }

    $content = [System.Collections.Generic.List[string]]::new()
    $content.Add($generatedNotice)
    $content.Add('')
    $content.Add("# $($Command.Name)")
    $content.Add('')
    $content.Add('## Synopsis')
    $content.Add('')
    $content.Add($synopsis)
    $content.Add('')
    $content.Add('## Description')
    $content.Add('')
    $content.Add($description)
    $content.Add('')
    $content.Add('## Syntax')
    $content.Add('')
    $content.Add('```powershell')
    $content.Add((ConvertTo-MarkdownText -Value (Get-Command -Name $Command.Name -Syntax)))
    $content.Add('```')
    $content.Add('')
    $content.Add('## Parameters')
    $content.Add('')

    if (@($parameters).Count -eq 0) {
        $content.Add('This cmdlet has no cmdlet-specific parameters.')
        $content.Add('')
    }
    else {
        foreach ($parameter in $parameters) {
            $parameterHelp = $helpParameters[$parameter.Name]
            $content.Add("### -$($parameter.Name)")
            $content.Add('')
            $content.Add((ConvertTo-MarkdownText -Value $parameterHelp.Description))
            $content.Add('')
            $content.Add('| Property | Value |')
            $content.Add('| --- | --- |')
            $content.Add(('| Type | `{0}` |' -f (ConvertTo-MarkdownTableCell -Value (Get-ParameterTypeName -Parameter $parameter))))
            $content.Add("| Required | $(ConvertTo-MarkdownTableCell -Value $parameterHelp.Required) |")
            $content.Add("| Position | $(ConvertTo-MarkdownTableCell -Value $parameterHelp.Position) |")
            $content.Add("| Default value | $(ConvertTo-MarkdownTableCell -Value $parameterHelp.DefaultValue) |")
            $content.Add("| Accept pipeline input | $(ConvertTo-MarkdownTableCell -Value $parameterHelp.PipelineInput) |")
            $content.Add("| Accept wildcard characters | $(ConvertTo-MarkdownTableCell -Value $parameterHelp.Globbing) |")
            $aliases = @($parameter.Aliases)
            if (@($aliases).Count -gt 0) {
                $content.Add("| Aliases | $(ConvertTo-MarkdownTableCell -Value ($aliases -join ', ')) |")
            }
            $content.Add('')
        }
    }

    $examples = if ($help.PSObject.Properties['Examples']) {
        @($help.Examples.Example)
    }
    else {
        @()
    }
    if (@($examples).Count -gt 0) {
        $content.Add('## Examples')
        $content.Add('')
        $exampleNumber = 0
        foreach ($example in $examples) {
            $exampleNumber++
            $title = ConvertTo-MarkdownText -Value $example.Title
            $title = ($title -replace '^-+\s*', '' -replace '\s*-+$', '').Trim()
            if (-not $title) {
                $title = "Example $exampleNumber"
            }
            $content.Add("### $title")
            $content.Add('')
            $content.Add('```powershell')
            $content.Add((ConvertTo-MarkdownText -Value $example.Code))
            $content.Add('```')
            $remarks = ConvertTo-MarkdownText -Value $example.Remarks
            if ($remarks) {
                $content.Add('')
                $content.Add($remarks)
            }
            $content.Add('')
        }
    }

    $inputs = if ($help.PSObject.Properties['InputTypes']) {
        @($help.InputTypes.InputType | ForEach-Object { ConvertTo-MarkdownText -Value $_.Type.Name } | Where-Object { $_ })
    }
    else {
        @()
    }
    if (@($inputs).Count -gt 0) {
        $content.Add('## Inputs')
        $content.Add('')
        foreach ($inputType in $inputs) {
            $content.Add(('- `{0}`' -f $inputType))
        }
        $content.Add('')
    }

    $outputs = if ($help.PSObject.Properties['ReturnValues']) {
        @($help.ReturnValues.ReturnValue | ForEach-Object { ConvertTo-MarkdownText -Value $_.Type.Name } | Where-Object { $_ })
    }
    else {
        @()
    }
    if (@($outputs).Count -gt 0) {
        $content.Add('## Outputs')
        $content.Add('')
        foreach ($outputType in $outputs) {
            $content.Add(('- `{0}`' -f $outputType))
        }
        $content.Add('')
    }

    $notes = if ($help.PSObject.Properties['AlertSet']) {
        ConvertTo-MarkdownText -Value $help.AlertSet.Alert
    }
    else {
        ''
    }
    if ($notes) {
        $content.Add('## Notes')
        $content.Add('')
        $content.Add($notes)
        $content.Add('')
    }

    $links = if ($help.PSObject.Properties['RelatedLinks']) {
        @($help.RelatedLinks.NavigationLink | Where-Object { $_.LinkText -or $_.Uri })
    }
    else {
        @()
    }
    if (@($links).Count -gt 0) {
        $content.Add('## Related links')
        $content.Add('')
        foreach ($link in $links) {
            $text = ConvertTo-MarkdownText -Value $link.LinkText
            $uri = ConvertTo-MarkdownText -Value $link.Uri
            if ($text -and $uri) {
                $content.Add("- [$text]($uri)")
            }
            elseif ($uri) {
                $content.Add("- $uri")
            }
            else {
                $content.Add("- $text")
            }
        }
        $content.Add('')
    }

    return (($content -join $lineFeed).TrimEnd() + $lineFeed)
}

$module = Import-Module -Name $manifestPath -Force -PassThru -ErrorAction Stop
try {
    $commands = @($module.ExportedFunctions.Values | Sort-Object -Property Name)
    if ($commands.Count -eq 0) {
        throw "No exported functions were found in '$manifestPath'."
    }

    $expectedFiles = [ordered]@{}
    foreach ($command in $commands) {
        $expectedFiles["$($command.Name).md"] = Get-CommandReferenceContent -Command $command
    }

    $index = [System.Collections.Generic.List[string]]::new()
    $index.Add($generatedNotice)
    $index.Add('')
    $index.Add('# Avm.Authoring cmdlet reference')
    $index.Add('')
    $index.Add('This reference is generated from the comment-based help on the public PowerShell functions.')
    $index.Add('')
    $index.Add('| Cmdlet | Purpose |')
    $index.Add('| --- | --- |')
    foreach ($command in $commands) {
        $help = Get-Help -Name $command.Name
        $purpose = ConvertTo-MarkdownTableCell -Value $help.Synopsis
        $index.Add("| [$($command.Name)]($($command.Name).md) | $purpose |")
    }
    $expectedFiles['README.md'] = (($index -join $lineFeed).TrimEnd() + $lineFeed)

    $resolvedOutputPath = [System.IO.Path]::GetFullPath($OutputPath)
    $actualFiles = @{}
    if (Test-Path -LiteralPath $resolvedOutputPath -PathType Container) {
        foreach ($file in Get-ChildItem -LiteralPath $resolvedOutputPath -Filter '*.md' -File) {
            $actualFiles[$file.Name] = $file.FullName
        }
    }

    $differences = [System.Collections.Generic.List[string]]::new()
    foreach ($entry in $expectedFiles.GetEnumerator()) {
        if (-not $actualFiles.ContainsKey($entry.Key)) {
            $differences.Add("missing: $($entry.Key)")
            continue
        }

        $actual = [System.IO.File]::ReadAllText($actualFiles[$entry.Key]) -replace "`r`n?", $lineFeed
        if ($actual -cne $entry.Value) {
            $differences.Add("stale: $($entry.Key)")
        }
    }
    foreach ($actualName in $actualFiles.Keys) {
        if (-not $expectedFiles.Contains($actualName)) {
            $differences.Add("unexpected: $actualName")
        }
    }

    if ($Check) {
        if ($differences.Count -gt 0) {
            throw "Generated cmdlet documentation is out of date. Run './build.ps1 docs' and commit the result.`n$($differences -join $lineFeed)"
        }
        Write-Information "Cmdlet documentation is current: $($commands.Count) reference pages." -InformationAction Continue
        return
    }

    if (-not (Test-Path -LiteralPath $resolvedOutputPath -PathType Container)) {
        $null = New-Item -ItemType Directory -Path $resolvedOutputPath -Force
    }
    foreach ($actualName in $actualFiles.Keys) {
        if (-not $expectedFiles.Contains($actualName)) {
            Remove-Item -LiteralPath $actualFiles[$actualName] -Force
        }
    }
    foreach ($entry in $expectedFiles.GetEnumerator()) {
        $destination = Join-Path $resolvedOutputPath $entry.Key
        [System.IO.File]::WriteAllText($destination, $entry.Value, $utf8NoBom)
    }

    Write-Information "Generated $($commands.Count) cmdlet reference pages in '$resolvedOutputPath'." -InformationAction Continue
}
finally {
    Remove-Module -ModuleInfo $module -Force -ErrorAction SilentlyContinue
}
